elasticsearch/readme.md, etl/build.gradle
New task etlGptCollectionsToLocalApi which queries ncei-md geoportal for collection records with browse graphics.  GRHSST records are exclueded as they are loaded separately.
=> New gradle task in etl to load collection metadata records

api/Dockerfile, client/Dockerfile, client/docker-nginx.conf, docker-compose.override.yml.sample, docker-compose.yml, elasticsearch/config/elasticsearch.yml, elasticsearch/config/shield/logging.yml, elasticsearch/config/shield/roles.yml, elasticsearch/config/shield/users, elasticsearch/config/shield/users_roles, elasticsearch/docker-es/Dockerfile, readme.md
Reverts cedardevs/onestop#178
After examining what happened with the accidental pull request to master instead of develop... we've decided that:
1. That is a very easy mistake to make
1. We really aren't getting much value from the master branch
The revert revert will put the docker changes back onto master, then we'll do another pull request to pull in develop permanently.
=> Revert "Revert "Docker""

client/src/detail/DetailComponent.jsx, client/src/result/granules/list/GranuleListComponent.jsx
=> 200 legend repetition

api/src/integrationTest/groovy/ncei/onestop/api/SearchIntegrationTests.groovy, api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy, api/src/test/groovy/ncei/onestop/api/service/MetadataParserTest.groovy, api/src/test/resources/test-iso-point-cords-metadata.xml
=> Fix indexing of envelopes that cross the dateline

client/src/result/collections/collectionTile.css
=> #291 - fixed padding issue causing margin in maps on collectionTile

api-metadata/build.gradle, api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/ETLIntegrationTests.groovy, api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/ElasticsearchService.groovy, api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/ElasticsearchServiceTests.groovy, build.gradle, docker-compose.yml, geoportal-search/Dockerfile, geoportal-search/conf/WEB-INF/classes/gs/config/Config.js, geoportal-search/entrypoint.sh
=> 282 prefix fixes

client/package.json, client/src/utils/queryUtils.js, client/test/utils/queryUtilsSpec.js
Resolves #322. Also helps set us up for #315.
=> Customize how filters are encoded/decoded to/from the URL

client/src/detail/AccessView.jsx, client/src/detail/Detail.jsx
=> #258 - adding access tab content

client/src/root/Header.jsx, client/src/root/Logo.jsx, client/src/root/header.css, client/src/search/searchFields.css
=> Use a consistent logo

client/package-lock.json, client/src/common/input/Button.jsx, client/src/landing/Section508Landing.jsx, client/src/landing/section508.css, package-lock.json
=> #355 - BUT_TON IM_PROV_MENTS DE_PLOYYyyyYYnnnNnNn

client/src/common/Expandable.jsx, client/src/common/input/Checkbox.jsx, client/src/filter/Filters.jsx, client/src/filter/facet/Facet.jsx, client/src/filter/facet/FacetFilter.jsx, client/src/filter/facet/FacetFilterContainer.js, client/src/filter/facet/FacetTree.jsx, client/src/filter/time/TimeFilter.jsx, client/src/filter/time/TimeFilterContainer.js, client/src/reducers/domain/results.js, client/src/search/SearchFields.jsx, client/src/search/SearchFieldsContainer.js, client/src/utils/keywordUtils.js, client/test/utils/keywordUtilsSpec.js
=> 369 improve facet handling

client/src/filter/time/TimeFilter.jsx
Note that there were a few items listed in the story I chose not to implement. I left them there to document that they were things we might want to improve in the future, and why they are not part of this change. Overall, I consider them unnecessary for 508 support right now, unless we hear otherwise from our testers.
Closes #420
=> 420 time filter a11y

client/package-lock.json, client/src/search/map/Map.jsx
resolves #436 
Improving the styling of the text above the map was inherently weird because the animation originally expected that div to be fixed height for the map when it popped out. I was able to compensate by adjusting some margins/paddings/etc, and disallowed the text from showing until the other animation was complete. This makes for a better overall visualization. I went with coloring the background of the text a darker blue and 100% width, because it looked a bit weird to be two shades and centered.
=> #436 - cleaning up map animation text styling and behavior

api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataParser.groovy, api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/MetadataParserTest.groovy, api-metadata/src/test/resources/test-iso-metadata.xml, e2e-tests/src/test/resources/test-iso-metadata-collection.xml, e2e-tests/src/test/resources/test-iso-metadata.json, index-configuration/src/main/resources/searchIndex.json, index-configuration/src/main/resources/stagingIndex.json
=> 465 update misc parsing

client/src/utils/keywordUtils.js
Keyword util helper function to make it more clear what determines if keywords are coerced into a tree structure or not.
=> Minor refactor to label function.

api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataParser.groovy, api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/MetadataParserTest.groovy, api-metadata/src/test/resources/test-iso-metadata.xml, e2e-tests/src/test/resources/test-iso-metadata-collection.xml, e2e-tests/src/test/resources/test-iso-metadata.json, index-configuration/src/main/resources/searchIndex.json, index-configuration/src/main/resources/stagingIndex.json
=> #476 - citation parsing updates

api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataParser.groovy, api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/MetadataParserTest.groovy, api-metadata/src/test/resources/test-iso-metadata.xml, e2e-tests/src/test/resources/test-iso-metadata.json, index-configuration/src/main/resources/searchIndex.json, index-configuration/src/main/resources/stagingIndex.json
=> 474 high level fields

api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataParser.groovy, api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/MetadataParserTest.groovy, api-metadata/src/test/resources/test-iso-metadata.xml, e2e-tests/src/test/resources/test-iso-metadata-collection.xml, e2e-tests/src/test/resources/test-iso-metadata.json, index-configuration/src/main/resources/searchIndex.json, index-configuration/src/main/resources/stagingIndex.json
=> 467 update data formats parsing

client/src/actions/FlowActions.js, client/src/actions/SearchRequestActions.js, client/src/common/info/Help.jsx, client/src/detail/Detail.jsx, client/src/detail/DetailContainer.js, client/src/detail/SummaryView.jsx, client/src/reducers/behavior/request.js, client/src/reducers/ui/layout.js, client/src/utils/queryUtils.js, client/src/utils/urlUtils.js, client/test/utils/queryUtilsSpec.js
These are bug fixes that are not specifically part of 445, but need to be included in the release.
- Fix calling search extra times
- Fix granule 'load more' disrupting which tab the user is looking at, making it look broken.
=> 445 bug fixes only

api-search/src/integrationTest/groovy/org/cedar/onestop/api/search/SearchIntegrationTests.groovy, api-search/src/main/groovy/org/cedar/onestop/api/search/service/ElasticsearchService.groovy, client/src/actions/FlowActions.js, client/src/actions/LayoutActions.js, client/src/actions/SearchRequestActions.js, client/src/common/info/Help.jsx, client/src/detail/Detail.jsx, client/src/detail/DetailContainer.js, client/src/detail/SummaryView.jsx, client/src/filter/Filters.jsx, client/src/filter/FiltersContainer.jsx, client/src/filter/FiltersHidden.jsx, client/src/filter/FiltersHiddenContainer.jsx, client/src/reducers/behavior/request.js, client/src/reducers/ui/layout.js, client/src/result/AppliedFilters.jsx, client/src/result/AppliedFiltersContainer.js, client/src/result/collections/CollectionGrid.jsx, client/src/root/Root.jsx, client/src/root/RootContainer.jsx, client/src/utils/queryUtils.js, client/src/utils/urlUtils.js, client/test/reducers/ui/layoutSpec.js, client/test/utils/queryUtilsSpec.js, client/test/utils/urlUtilsSpec.js
=> 442 ui layout redux state

client/package-lock.json, client/src/common/defaultStyles.jsx, client/src/common/info/About.jsx, client/src/common/input/Button.jsx, client/src/common/input/Checkbox.jsx, client/src/detail/AccessView.jsx, client/src/detail/DescriptionView.jsx, client/src/detail/GranulesSummary.jsx, client/src/detail/Tabs.jsx, client/src/filter/Fieldset.jsx, client/src/filter/Filters.jsx, client/src/filter/facet/FacetFilter.jsx, client/src/filter/facet/FacetTree.jsx, client/src/filter/spatial/MapFilter.jsx, client/src/filter/time/TimeFilter.jsx, client/src/landing/FeaturedDatasets.jsx, client/src/landing/TopicsMenuButton.jsx, client/src/layout/Left.jsx, client/src/root/Header.jsx, client/src/root/HeaderLink.jsx, client/src/root/Root.jsx, client/src/root/banner/Banner.jsx, client/src/search/SearchFields.jsx, client/src/utils/resultUtils.js, client/test/utils/resultUtilsSpec.js
Fixes all the color contrast issues mentioned in #513, as well as a very basic starting pass at figuring out how to structure theme information so that it's easy to substitute.
Fixed the warnings to close out #513 entirely.
=> Color contrast fixes

client/src/utils/resultUtils.js, client/test/utils/resultUtilsSpec.js
closes #571, also fixes some of the cloud protocols based on example data that is using real cloud protocols.
=> Fix for #571.

api-metadata/build.gradle, api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/controller/UploadController.groovy, api-metadata/src/main/resources/application.yml, api-metadata/src/main/resources/templates/upload.html, api-search/build.gradle
=> 631 upload form

api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/ETLIntegrationTests.groovy, api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/IntegrationTestConfig.groovy, api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/LoadIntegrationTests.groovy, api-metadata/src/integrationTest/resources/test-securitydisabled.yml, api-metadata/src/main/resources/application.yml
=> fixes for master hopefully

readme.md
See https://grantsonline.rdc.noaa.gov/flows/publicSearch/begin.do
=> Fix NOAA award number

client/src/common/MapThumbnail.jsx, client/src/helmet/Meta.jsx, client/src/root/Footer.jsx
Closes #751
Don't forget to follow the wiki instructions to manually apply these changes to master as well.
=> 751 wcag hot fix

api-search/src/main/groovy/org/cedar/onestop/api/search/security/config/LoginGovAuthenticationFailureHandler.groovy, api-search/src/main/groovy/org/cedar/onestop/api/search/security/config/SecurityConfig.groovy
=> redirect to homepage on login failure

client/src/detail/AccessView.jsx
=> add 'search data' section for search links in collection access tab

api-search/src/integrationTest/groovy/org/cedar/onestop/api/search/TimeFilterIntegrationTests.groovy, api-search/src/integrationTest/resources/generic/time_filter/README.md, api-search/src/integrationTest/resources/generic/time_filter/bulkData.txt, api-search/src/main/groovy/org/cedar/onestop/api/search/service/ElasticsearchService.groovy, api-search/src/main/groovy/org/cedar/onestop/api/search/service/SearchRequestParserService.groovy, api-search/src/test/groovy/org/cedar/onestop/api/search/service/SearchRequestParserServiceTest.groovy
Logic & tests fixed. Only thing we may want to consider is moving the readme.md from the api-search integration test data folder to an actual location in a high level docs directory, but this may just be another task in a later tech debt epic.
=> 850 time logic fix

api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/LoadIntegrationTests.groovy, api-metadata/src/integrationTest/resources/data/BadFiles/noIdExample.xml, api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataManagementService.groovy, api-search/schema/openapi.yml, client/package.json, gradle.properties, helm/onestop/Chart.yaml, skaffold.yaml
Creating a PR to also merge this fix into the release branch as a hotfix.
=> #861 file identifer bug (hotfix)

api-metadata/build.gradle, api-search/build.gradle, client/.retireignore.json, owasp-suppressions.xml
Hotfix version of PR #880 
Changes created with `git format-patch -3 aa464f2accae0ef8bfcb72ec836813307b1afb20` on the fix-vunerabilities branch
=> Apply fix-vunerabilities branch as a hotfix to release/2.x

api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataManagementService.groovy
=> Hotfix for double-prefix of flattened granules

docs/development/release-checklist.md
Update docs to include check for serviceLinks
=> add check for DEM service links

build.gradle, elastic-common/build.gradle
Fix CVEs in preparation for tagging 2.2
=> CVE version fixes

api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/MigrationIntegrationTest.groovy, api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataManagementService.groovy, docs/design/iso-indexing-mapping.md
Resolves #942 
We needed to be more specific about what type of document we are re-keying.
=> 942 granule duplicates

client/src/components/collections/detail/AccessView.jsx
Added service links to the collection access tab.
=> Service links access tab

client/src/components/helmet/Meta.jsx
Resolves #949 
Implementing this suggestion fixed it- 
https://github.com/nfl/react-helmet/issues/373#issuecomment-392650715
=> Meta creates Helmet with properties instead of elements

client/src/components/filters/facet/FacetFilter.jsx, client/src/components/filters/spatial/MapFilter.jsx, client/src/components/filters/time/TimeFilter.jsx
Got rid of the WAVE warnings, but not sure about fieldset placement.  Seeking feedback.
=> 795 orphaned form label

client/src/components/about/About.jsx
Updated access statement on about page to reflect current Level AA status on all features.
=> update accessibility statement

client/src/components/results/Results.jsx, client/src/components/results/granules/GranuleList.jsx, client/src/components/results/granules/GranuleListLegend.jsx, client/src/components/results/granules/GranuleListLegendContainer.jsx, client/src/components/results/granules/GranuleListResult.jsx
resolves #975
changes granule list header (due to general confusion of wording based on review)
=> Ui tweaks 2.3

.circleci/config.yml, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/ETLIntegrationTests.groovy, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/KafkaIngestIntegrationSpec.groovy, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/LoadIntegrationTests.groovy, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/MigrationIntegrationTest.groovy, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/SitemapETLIntegrationTests.groovy, admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/UploadIntegrationTests.groovy, search/src/integrationTest/groovy/org/cedar/onestop/api/search/SearchControllerIntegrationTests.groovy, search/src/integrationTest/groovy/org/cedar/onestop/api/search/SpatialFilterIntegrationTests.groovy, search/src/integrationTest/groovy/org/cedar/onestop/api/search/TimeFilterIntegrationTests.groovy, search/src/integrationTest/groovy/org/cedar/onestop/api/search/TrendingSearchServiceWithCustomBlacklistConfigSpec.groovy, search/src/integrationTest/groovy/org/cedar/onestop/api/search/TrendingSearchServiceWithDefaultBlacklistConfigSpec.groovy
=> 1006 integration test es prefix

admin/src/main/groovy/org.cedar.onestop.api.admin/service/KafkaConsumerService.groovy, admin/src/test/groovy/org/cedar/onestop/api/admin/service/LoadKafkaMsgServiceTest.groovy
=> Handle tombstones by deleting metadata when incoming value is null

admin/src/main/groovy/org.cedar.onestop.api.admin/service/MetadataManagementService.groovy
=> Log the results of bulk requests

admin/src/main/groovy/org.cedar.onestop.api.admin/service/KafkaConsumerService.groovy, admin/src/test/groovy/org/cedar/onestop/api/admin/service/LoadKafkaMsgServiceTest.groovy, build.gradle
=> Upgrade schemas and use the new default-filling capability

admin/build.gradle, build.gradle, geoportal-search/Dockerfile, search/build.gradle
=> update tomcat base image

registry/src/main/groovy/org/cedar/onestop/registry/api/MetadataRestController.groovy, registry/src/main/groovy/org/cedar/onestop/registry/api/PublisherController.groovy, registry/src/main/java/org/cedar/onestop/registry/stream/StreamFunctions.java, registry/src/main/java/org/cedar/onestop/registry/stream/TopologyBuilders.java, registry/src/test/groovy/org/cedar/onestop/registry/api/MetadataRestControllerSpec.groovy, registry/src/test/groovy/org/cedar/onestop/registry/stream/FullTopologySpec.groovy, registry/src/test/groovy/org/cedar/onestop/registry/stream/StreamFunctionsSpec.groovy
Resolves #1105 
When you done with this review, we need to apply the same changes to the psi repo and push code to gitlab.
=> 1105 sanitize ids

helm/onestop-dev/values.yaml, helm/onestop-registry/values.yaml, registry/src/main/java/org/cedar/onestop/registry/service/KafkaBeanConfig.java, registry/src/main/resources/application.yml
=> 1127 message compression

client/src/components/collections/detail/DetailGrid.jsx, client/src/components/common/input/Button.jsx, client/src/components/landing/FeaturedDatasets.jsx, client/src/components/layout/Content.jsx, helm/onestop-search/values.yaml, search/src/main/groovy/org/cedar/onestop/api/search/controller/UiConfig.groovy
=> 532 featured datasets enhance

README.md
I believe it's standard practice to update copyright every year of a working project.
=> Update copyright in readme to 2020.

elastic-common/src/main/java/org/cedar/onestop/elastic/common/DocumentUtil.java, search/src/main/groovy/org/cedar/onestop/api/search/service/ElasticsearchService.groovy
Full counts now returned for ES7 deployments to maintain OSIM expected behavior
Resolves #1164
=> total hits returned for both ES6 and ES7 now

client/src/components/collections/detail/AccessView.jsx
=> Add default link text if non is available.

client/src/components/collections/detail/AccessView.jsx
addresses #985 on the release/2.4 path.
=> 1147 access link 2.4

client/src/components/filters/spatial/BoundingBoxEffect.js, client/test/components/filters/spatial/BoundingBoxEffect.test.js
=> 1198 apply bounding coordinates na n

registry/src/integrationTest/groovy/org/cedar/onestop/registry/RegistryIntegrationSpec.groovy, registry/src/main/groovy/org/cedar/onestop/registry/api/PublisherController.groovy, registry/src/main/groovy/org/cedar/onestop/registry/service/Publisher.groovy, registry/src/test/groovy/org/cedar/onestop/registry/service/PublisherSpec.groovy
Support for operations on PATCH requests received through HTTP input
resolves #1263
=> 1263 patch ops

elastic-common/src/main/resources/mappings/analysis_error_collectionIndex.json, elastic-common/src/main/resources/mappings/analysis_error_granuleIndex.json
=> 1251 ae mapping

registry/build.gradle
Added runtime dependency to gradle.build resolves startup error. Closes #1300
=> Added runtime hibernate-validator library

.circleci/config.yml, build.gradle.kts, owasp-suppressions.xml
=> 1327 owasp check

data-common/src/main/java/org/cedar/onestop/data/util/JsonUtils.java, data-common/src/test/groovy/JsonUtilsSpec.groovy, elastic-common/src/main/java/org/cedar/onestop/elastic/common/ElasticsearchReadService.java, test-common/src/main/java/org/cedar/onestop/test/common/Main.java
=> simplify toJson behavior

docs/public-user.md, docs/public-user/api/antimeridian.md, docs/public-user/api/community-standards.md, docs/public-user/api/query-syntax.md, docs/public-user/api/quickstart.md, docs/public-user/api/requests.md
=> 1084 public user api docs update

elastic-common/src/main/resources/mappings/search_collectionIndex.json, elastic-common/src/main/resources/mappings/search_flattened_granuleIndex.json, elastic-common/src/main/resources/mappings/search_granuleIndex.json, indexer/src/main/java/org/cedar/onestop/indexer/util/TransformationUtils.java, indexer/src/test/groovy/org/cedar/onestop/indexer/util/TransformationUtilsSearchSpec.groovy, search/src/main/groovy/org/cedar/onestop/api/search/service/ElasticsearchService.groovy, search/src/main/groovy/org/cedar/onestop/api/search/service/SearchRequestParserService.groovy, search/src/main/java/org/cedar/onestop/api/search/service/DocumentationService.java, search/src/main/resources/static/openapi.yaml, search/src/test/groovy/org/cedar/onestop/api/search/service/SearchRequestParserServiceTest.groovy
closes #453 
I wasn't sure on the naming of my new facets. "linkAccessTypes" in particular felt a little long-winded, but I didn't know what else to call it that would still be clear.
=> 453 granule specific filters
