client/src/utils/queryUtils.js

This is a follow up PR to #179 wherein we remove the develop branch and switch back to developing against master.
FYI for @cedardevs/foamcat developers! Develop against master from now on!

Pull in and discontinue develop branch

---

client/src/common/link/LinkComponent.jsx
client/src/root/FooterComponent.jsx
client/src/utils/urlUtils.js
client/test/utils/urlUtilsSpec.js

Fixes #199 
Note: I think this also fixes the fact that the `here` link in the help wasn't being styled; it's `href` attribute wasn't being rendered, so it wasn't being colored like a link.

199 url warning

---

client/src/search/map/MapComponent.jsx

I'm letting it zoom in further than the thumbnail map because the full maps are big enough to still give you enough context. Note that this also applies to the drop-down map for drawing a spatial filter.
I could be convinced that 6 is a better number. Would be nice for someone else to take a look.
Resolves #210

Add a max zoom to the main map component

---

client/package.json
client/src/detail/DetailComponent.jsx
client/src/detail/detail.css

I found a small, simple react component which figures out how many lines long a block of text is and truncates it.
I played around with the styling a fair amount but ended up doing something very simple because I thought it fit better than other things I was trying (buttons, arrows, etc). I'm certainly open to other ideas on styling if you have them.
Also I thought about trying to do something about how wide the paragraphs get, but decided that there really wasn't a good way to do that without something else to put to the right of the descriptions. In the future we'll index citation information and put that there as requested, but I don't think there's anything else that fits well there at the moment.
Resolves #208, at least for the time being until we add citation info.

Truncate long descriptions

---

api-metadata/build.gradle
api-search/build.gradle
client/build.gradle

Added a new tag for docker images: 'latest-SNAPSHOT', which will be the primary tag for CU deployment. This should be pushed to docker hub with every successful build.
The current travis build will only actually push latest snapshot images to docker hub when we merge it to master.

image tag 'latest-SNAPSHOT'

---

client/src/common/MapThumbnailComponent.jsx
client/src/detail/DetailComponent.jsx
client/src/detail/SummaryView.jsx
client/src/detail/detail-container.css
client/src/detail/detail-views.css
client/src/result/collections/CollectionTileComponent.jsx
client/src/result/granules/MapContainer.js
client/src/search/map/MapComponent.jsx
client/src/utils/geoUtils.js

Closes #255. 
Summary of changes:
- Created a summary view component to reside within the detail view component. We may want to rename these later so it's clearly the collection view. This is the first step in having a future tab bar to swap out the view of the collection.
- Made MapThumbnailComponent support interactive use (stays not-interactive on results grid view but can be zoomed/panned in collection summary view)
- Changed base map of all maps to satellite imagery (thought it looked nicer!)
- Fixed bug #273 
- Fixed bug #274 
- Made the title expandable so users can actually read the whole thing
I didn't try to change the style of the modal here, but rather focused on just the content and functionality of the summary view. It made sense to me that we'd put our heads together on …

255 Feature/collection summary view

---

api-search/src/main/resources/application.yml
build.gradle

- version info is automatically updated as long as nothing in the deployment overwrites the value later. (no change needed)
- added buildDate to the info endpoint
Test response from the info endpoint now looks like:
{version: "2.0.0-SNAPSHOT", buildDate: "2017-10-27"}
resolves #230

Include build date on info endpoint.

---

api/src/main/resources/application.yml
build.gradle

See also review #289 for the 2.0 milestone.
Verified that a clean build the info endpoint returns `{"version":"1.2.1-SNAPSHOT","buildDate":"2017-10-30"}`, and that these values are correctly built into application.yml inside the war.

Actually resolves #230 for the 1.3 milestone.

---

client/src/detail/GranuleTab/GranuleView.jsx
client/src/utils/ProtocolUtils.js
client/test/utils/protocolUtilsSpec.js

Closes #383.
A question for this review: Based on the spreadsheet, there's some interpretation that the labels should be distinct.
OPeNDAP:OPeNDAP -> OPeNDAP root URL
OPeNDAP:Hyrax -> OPeNDAP Hyrax server
UNIDATA:THREDDS ->THREDDS Catalog
I interpreted the task to mean we should continue to bucket them into less specific labels, since the badges are just indicators. I also assumed that the additional protocols were too uncertain to add yet. (Also, if we add too many protocols, we're going to run into difficulty having enough distinct colors).

383 ui granule protocols

---

client/src/search/map/Map.jsx

Map open and close are internal state transitions, allowing us to toggle display: none correctly.
Now the map should animate correctly when opening and closing (including the text instruction part which was showing strangely during animation), while still correctly removing the map from the dom with display:none for screen readers and tab order.
Resolves #521

Fix map animation.

---

client/src/common/info/Help.jsx

After running through story 278 which I closed as a won't fix, I found that we can use regex queries with query_string but there is no way to help the user by validating input and giving a context message like we do with empty search fields or queries that start with * or ?. The main problem is that Elastic Search can handle so many of the reserved characters that to validate search entries at the client level would be problematic.
So I added information to the help page for using a regex with the search field.

Add help message with regex search information.

---

api-search/build.gradle
api-search/src/main/groovy/org/cedar/onestop/api/search/security/config/LoginGovAuthorizationRequestResolver.groovy
api-search/src/main/groovy/org/cedar/onestop/api/search/security/config/LoginGovConfiguration.groovy
api-search/src/main/groovy/org/cedar/onestop/api/search/security/config/NonceUtil.groovy
api-search/src/main/groovy/org/cedar/onestop/api/search/security/controller/LoginController.groovy
api-search/src/main/resources/application.yml
kubernetes/deployments/onestop-api-search.yaml

Login.gov requires a nonce field to be generated for each session. 
This is a first pass on using the session id to generate a random 32 character string. We store this IN MEMORY until we get it back (which should be almost immediately) and then remove it. We met the basic requirements specified by login.gov but going forward we may consider using a hash instead of a random number generator. 
From login.gov docs- 
>nonce
A unique value at least 32 characters in length used to verify the integrity of the id_token and mitigate replay attacks. This value should include per-session state and be unguessable by attackers. This value will be present in the id_token of the token endpoint response, where clients will verify that the nonce claim value is equal to the value of the nonce parameter …

769  nonce

---

api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/LoadIntegrationTests.groovy
api-metadata/src/integrationTest/resources/data/BadFiles/noIdExample.xml
api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataManagementService.groovy

Users were seeing a CONFLICT where they should have seen BAD_REQUEST caused by submitting a file with no identifiers. We now check for that before trying to find and update pre-existing docs.

disallow docs with no fileId or doi

---

api-metadata/build.gradle
api-search/build.gradle
client/build.gradle
client/package-lock.json
skaffold.yaml

Hotfix version of #886.
Created with `git format-patch -1` on 878-simplify-artifact-names-for-deployment branch.

Remove version from artifact names.

---

client/src/components/header/HeaderLink.jsx

Used color from topic icons for a contrast ratio of 5.38:1 
Use https://webaim.org/resources/contrastchecker/ to check

increase headerlink hover color contrast

---

client/src/actions/routing/CollectionSearchRouteActions.js
client/src/actions/routing/CollectionSearchStateActions.js
client/src/components/cart/CartItem.jsx
client/src/components/common/ui/ListView.jsx
client/src/components/filters/FilterHeading.jsx
client/src/components/filters/collections/CollectionFilters.jsx
client/src/components/filters/collections/CollectionSearch.jsx
client/src/components/filters/collections/CollectionSearchContainer.js
client/src/components/filters/facet/FacetFilter.jsx
client/src/components/filters/granules/GranuleFilters.jsx
client/src/components/filters/spatial/MapFilter.jsx
client/src/components/header/Header.jsx
client/src/components/layout/Layout.jsx
client/src/components/results/collections/CollectionCard.jsx
client/src/components/results/collections/Collections.jsx
client/src/components/results/granules/GranuleList.jsx
client/src/components/results/granules/GranuleListLegend.jsx
client/src/components/results/granules/GranuleListResult.jsx
client/src/components/root/Root.jsx
client/src/reducers/search/collectionFilter.js
client/test/actions/routing/CollectionSearchRouteActions.test.js
client/test/reducers/search/collectionFilter.test.js

Resolves #800 
Functionally, this is ready for review. 
Summary of changes-
- hidden h1 on result pages
- header structure level on all list result views (collections, granules, cart). 
- text box has local state for input, queryText only set after submit
- commas in the search result header (e.g. showing 1,000 of 10,000) 
There is an action, [`collectionUpdateQueryText()`](https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/src/actions/routing/CollectionSearchStateActions.js), that is no longer needed by the code, but is [used in a test as a setup step](https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/test/actions/routing/CollectionSearchRouteActions.test.js#L66). We also need to remove [these tests for …

800 search context order

---

build.gradle

This resolves one of the vulnerabilities, but there are still two from kafka but semere is working on upgrading those.

resolve jackson dependency CVE

---

client/src/utils/geoUtils.js

It was what we assumed- a check for null was wrongly assuming 0 was unwanted.

fix for zero coordinates bug

---

client/src/components/filters/collections/CollectionMapContainer.js
client/src/components/filters/granules/GranuleMapContainer.js
client/src/components/filters/spatial/Map.jsx

Turns out we just hardcoded a watch in the map to watch the state of the 'collectionFilter'. Map the filterType a prop and passed it in from the container.

map accepts filterType to watch

---

client/src/actions/routing/CollectionDetailRouteActions.js
client/test/actions/routing/CollectionDetailRouteActions.test.js

This change conditionally fetches granule count based on filters existing or not. 
However, when I comment out 'dispatch(granuleMatchingCountRequested())` completely, I cant really tell a difference. The granule count seems accurate either way.

only request granule count if filters are applied

---

client/src/components/analytics/GoogleAnalytics.jsx
docs/deployment/feature-toggles.md
helm/api-search/values.yaml

Before these changes, specifying multiple tracking IDs would only send the first one under profiles. This is because additional trackers must be named and the one that is unnamed is the 'default', as in `reactGaOptions.alwaysSendToDefaultTracker`. 
These changes allow for multiple trackers. I also updated the documentation. 
To review this and debug google analytics in general, I highly recommend the google analytics debugger chrome extension.

969 analytics fix

---

.circleci/config.yml
api-metadata/build.gradle
api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/ETLIntegrationTests.groovy
api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/MigrationIntegrationTest.groovy
api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/ETLService.groovy
api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/Indexer.groovy
api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/KafkaConsumerService.groovy
api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/service/MetadataManagementService.groovy
api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/IndexerTest.groovy
api-metadata/src/test/groovy/org/cedar/onestop/api/metadata/service/LoadKafkaMsgServiceTest.groovy
api-metadata/src/test/resources/parsed-record-no-discovery-or-analysis.json
api-metadata/src/test/resources/parsed-record-with-default-discovery.json
api-metadata/src/test/resources/test-iso-collection-type-1.xml
api-metadata/src/test/resources/test-iso-collection-type-2.xml
api-metadata/src/test/resources/test-iso-error-type.xml
api-metadata/src/test/resources/test-iso-granule-type.xml
build.gradle
docs/design/iso-indexing-mapping.md
elastic-common/src/main/resources/mappings/ES5/search_collectionIndex.json
elastic-common/src/main/resources/mappings/ES6/search_collectionIndex.json
elastic-common/src/main/resources/pipelines/collection_pipelineDefinition.json
elastic-common/src/main/resources/pipelines/collection_pipeline_ES5-6_Definition.json
helm/kibana/templates/deployment.yaml
helm/kibana/values.yaml
helm/onestop-dev/values.yaml
skaffold.yaml

OneStop now supports ParsedRecords that do not have Discovery (e.g., granules ingested via Kafka that were not XML files). The DefaultParser from cedardevs/schemas#16 is now used to extract minimally viable information from a ParsedRecord that has FileInformation, at least one FileLocation, and a COLLECTION Relationship. Afterward, an Analysis object is then added to the updated ParsedRecord. Furthermore, validation steps have been cleaned up somewhat to minimize redundant errors (but there is still some improvement to do for a future task -- see #989 for more info). Lastly, the preferred way of determining if a record is a granule has changed per #731. This last bit now means a collection may have a non-null `parentIdentifier`, and granules **_must_** have a `hierarchyLevelName` value …

972 default kafka indexing

---

.circleci/config.yml
admin/src/integrationTest/groovy/org/cedar/onestop/api/admin/MigrationIntegrationTest.groovy
search/build.gradle

Simplify the build:
- Still builds the subprojects in parallel jobs
- Each job does all the steps for its subproject, rather than handing off between multiple jobs
- Test result capturing is working for the `admin` and `search` jobs
- `e2e` and `check-owasp-cve` now *only* run as part of the nightly build
Possible future improvements:
- The caching still does not seem to be fully functional, e.g. the `checkout` job is still downloading gradle every time
- The `finalize` step incurs nearly a full minute of time to attach the workspace from previous steps... but all it's doing is publishing to codecov and saving the cache. A possible future approach is:
- Publish codecov info in each of the `admin`, `client` and `search` jobs, see if codecov can stitch the reports together?
- Split the …

Experiment with build

---

.circleci/config.yml
client/jest.config.js

Updates circle config such that it:
- Builds and publishes all onestop and psi modules
- Captures all test results
- Saves html test reports as artifacts
- Publishes coverage reports for all tests
- **Actually caches the gradle home directory**
Resolves #1029

1029 update circle

---

.circleci/config.yml
build.gradle
helm/elasticsearch/values.yaml
helm/kibana/values.yaml
kafka-common/build.gradle
owasp-suppressions.xml
registry/build.gradle

- addresses latest CVE vulnerability checks
- included upgrade to avro 1.8.2->1.9.1 (which removed the vulnerable jackson-mapper-asl)
- we confirmed avro upgrade did not negatively affect system when having data loaded using 1.8.2, then reading in 1.9.2

Owasp jan8 2020

---

client/src/components/results/granules/GranuleAccessLink.jsx
client/src/utils/resultUtils.js

- fallback link title is now protocol from metadata (prevent losing info when there are multiple links of same protocol type - particularly unknown ones)
- two unidata types added to THREDDS protocol category
resolves #1135
Before:
After:

Fix protocol and links

---

indexer/src/main/java/org/cedar/onestop/indexer/util/ElasticsearchService.java

This PR resolves #1248 where it was noted that the new A&E indices were not ensured and not consistently being created when the Indexer was updated. This should fix that!

1248-Ensure Indices

---

buildSrc/src/main/kotlin/utils.kt
elastic-common/src/main/resources/mappings/search_collectionIndex.json
elastic-common/src/main/resources/mappings/search_flattened_granuleIndex.json
elastic-common/src/main/resources/mappings/search_granuleIndex.json
elastic-common/src/test/resources/test/data/generic/field_query/bulkData.txt
elastic-common/src/test/resources/test/data/generic/field_query/bulkDataES6.txt
elastic-common/src/test/resources/test/data/generic/field_query/index.json
search/src/integrationTest/groovy/org/cedar/onestop/api/search/FieldQueryIntegrationTests.groovy
search/src/main/groovy/org/cedar/onestop/api/search/controller/GlobalDefaultExceptionHandler.groovy
search/src/main/groovy/org/cedar/onestop/api/search/service/SearchRequestParserService.groovy
search/src/main/java/org/cedar/onestop/api/search/service/DocumentationService.java
search/src/main/resources/static/openapi.yaml
search/src/test/groovy/org/cedar/onestop/api/search/service/SearchRequestParserServiceTest.groovy

closes #1430 
The big feature here is the addition of a `fieldQuery` query type, which takes a `field` and `value` to search against, and supports (single-level) nested fields. Unlike the full-text search, this is only useful for non-text fields and I added a boolean parameter to control whether the query is ran as a `match` or a `wildcard`, defaulting to `match`. In the `openapi.yml` I specifically included an enum whitelist of the valid `fields` you can query against, but I did not include app-level validation for that so it's only enforced at the schema validation level. I mostly did that because I wasn't sure if that was the best approach or if I should not have a whitelist at all and the search API user can just search against any field they want.
This PR also changes the …

1430 search link url

---

client/package-lock.json
registry/src/main/groovy/org/cedar/onestop/registry/api/RootController.groovy
search/src/main/groovy/org/cedar/onestop/api/search/controller/DocumentationController.groovy
search/src/main/groovy/org/cedar/onestop/api/search/service/ApiRootGenerator.groovy
search/src/test/groovy/org/cedar/onestop/api/search/service/ApiRootGeneratorSpec.groovy
skaffold.yaml

Basically all I did was copy the `ApiRootGenerator` service that existed in `registry` into `search`, and then utilized the `api.root.url` Spring config value to provide an API root prefix for both `registry` and `search` to create the proper URL for redirecting to their respective `opanapi.yaml` documents.

Search/Registry API forwarding at root endpoint
